/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactive.restful.web.service;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
